name: Build EXE

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x

    - name: Compile EXE
      run: |
        csc FontCleanerGUI.cs /target:winexe /out:FontCleanerGUI.exe

    - name: Upload EXE
      uses: actions/upload-artifact@v4
      with:
        name: FontCleanerGUI
        path: FontCleanerGUI.exe
